Ft/bus 106 Adding metrics register logic
valitydev/exporter-tech-metrics pull request #17
Opened 2024-07-29 08:46 UTC by Gretchen-z

Adding metrics register logic

2024-07-29 10:16 UTC, echerniak requested changes

2024-07-29 10:16 UTC, echerniak commented on src/main/java/dev/vality/exporter/tech/metrics/service/OpenSearchService.java
>                                                                  .should(new Query(new MatchPhraseQuery.Builder()
Тут точно `should`?

2024-07-29 10:16 UTC, echerniak commented on src/main/java/dev/vality/exporter/tech/metrics/service/OpenSearchService.java
>                                                                  .should(new Query(new MatchPhraseQuery.Builder()
Этот запрос ещё кажется можно упростить, убрав совсем блок `mustNot` и вместо этого поле request искать по значению `v2/processing`

2024-07-29 10:16 UTC, echerniak commented on src/main/java/dev/vality/exporter/tech/metrics/service/OpenSearchService.java
>                                                                  .should(new Query(new MatchPhraseQuery.Builder()
И тут тоже `should` нужно поменять, иначе он вернет все логи с обращениями к ingress-controller'у, а не только те, что входят в диапозон http-кодов.

2024-07-29 10:16 UTC, echerniak commented on src/main/java/dev/vality/exporter/tech/metrics/service/OpenSearchService.java
>                                                                  .should(new Query(new MatchPhraseQuery.Builder()
Лучше менять на `filter`, поскольку `must`/`should` ещё [влияют](https://www.elastic.co/guide/en/elasticsearch/reference/8.14/query-dsl-bool-query.html) на `score` документа (чем он выше, тем выше документ будет в возвращаемой выборке). А у нас тут всё строго - либо документ есть в выборке, либо нет.

2024-07-29 10:16 UTC, echerniak commented on src/main/java/dev/vality/exporter/tech/metrics/service/OpenSearchService.java
>                                                                  .mustNot(new BoolQuery.Builder()
Этот блок можем попробовать убрать, сходу не нашел примеров, чтобы это условие что-то полезное фильтровало

2024-07-29 10:16 UTC, echerniak commented on src/main/java/dev/vality/exporter/tech/metrics/service/OpenSearchService.java
>                                                                  .should(new Query(new MatchPhraseQuery.Builder()
Предлагаю во всех запросах передавать `size(10000)` (сейчас в последнем запросе передаем 500), а сам параметр (`10000`) вынести в статичное поле класса по аналогии с остальными константами.

2024-07-29 10:16 UTC, echerniak commented on src/main/java/dev/vality/exporter/tech/metrics/service/ApiHttpCodesService.java
> +                registeredMetricsSize, capiHttpCodeData.size(), wapiHttpCodeData.size());
Вот этот лог я бы сделал уровня `debug` и обернул в `if (log.isDebugEnabled())` чтобы мы считали количество метрик только когда установлен соответствующий уровень логирования. Иначе сейчас мы будем считать их всегда, даже когда нам не нужно будет писать этот лог.

2024-07-29 13:02 UTC, Gretchen-z commented on src/main/java/dev/vality/exporter/tech/metrics/service/OpenSearchService.java
>                                                                  .should(new Query(new MatchPhraseQuery.Builder()
- `should` заменила на `filter`
- `mustNot` удалила, поиск по request изменила на `v2/processing`
- `size(10000)` вынесла в переменную, добавила в последний запрос

2024-07-29 13:02 UTC, Gretchen-z commented on src/main/java/dev/vality/exporter/tech/metrics/service/OpenSearchService.java
>                                                                  .should(new Query(new MatchPhraseQuery.Builder()
should заменила на filter

2024-07-29 13:02 UTC, Gretchen-z commented on src/main/java/dev/vality/exporter/tech/metrics/service/OpenSearchService.java
>                                                                  .mustNot(new BoolQuery.Builder()
mustNot удалила

2024-07-29 13:04 UTC, Gretchen-z commented on src/main/java/dev/vality/exporter/tech/metrics/service/ApiHttpCodesService.java
> +                registeredMetricsSize, capiHttpCodeData.size(), wapiHttpCodeData.size());
добавила в `ApiHttpCodesService` и в `MachinesFailedService`

2024-07-30 07:20 UTC, echerniak approved these changes

2024-07-30 07:26 UTC, merged