Fixing finding withdrawal data
valitydev/exporter-tech-metrics pull request #19
Opened 2024-08-01 08:23 UTC by Gretchen-z

2024-08-01 13:34 UTC, echerniak requested changes

2024-08-01 13:34 UTC, echerniak commented on src/main/java/dev/vality/exporter/tech/metrics/service/MachinesFailedService.java
> +                .map(id -> id.endsWith("/1") ? id.substring(0, id.length() - 2) : id)
Тут может быть не только `/1`, а `/` и любая цифра, надо это учесть в фильтре.

2024-08-01 13:34 UTC, echerniak commented on src/main/java/dev/vality/exporter/tech/metrics/service/MachinesFailedService.java
>                          list -> log.isDebugEnabled()
А вот этот фильтр (там еще 1 строка ниже, гитхаб не дал её выделить) что делает? Будто бы в случае дебаг-логирования он просто обрезает количество выплат до 10. Так не должно быть (ну или я криво распарсил код).

2024-08-01 14:52 UTC, Gretchen-z commented on src/main/java/dev/vality/exporter/tech/metrics/service/MachinesFailedService.java
>                          list -> log.isDebugEnabled()
да, я изначально ставила лимит 10, потому что иначе логи сильно забиваются, и на нас ругаются) подумала, что стоит оставить для дебага лимит

2024-08-01 14:55 UTC, Gretchen-z commented on src/main/java/dev/vality/exporter/tech/metrics/service/MachinesFailedService.java
> +                .map(id -> id.endsWith("/1") ? id.substring(0, id.length() - 2) : id)
здесь сделала regex на случай любой цифры или числа после /

2024-08-01 15:00 UTC, echerniak commented on src/main/java/dev/vality/exporter/tech/metrics/service/MachinesFailedService.java
>                          list -> log.isDebugEnabled()
Тут тогда лучше сделать вывод только 10 id в логи (и писать в том же логе настоящее количество выплат одним числом), но в обработку брать всё, что достали из опенсерча. Иначе возникает неочевидная логика, когда при изменении уровня логирования приложение начинает отдавать метрики не по всем упавшим выплатам.

2024-08-01 15:52 UTC, Gretchen-z commented on src/main/java/dev/vality/exporter/tech/metrics/service/MachinesFailedService.java
>                          list -> log.isDebugEnabled()
сделала вывод в логи 10, а обработку всех данных

2024-08-02 09:40 UTC, echerniak approved these changes

2024-08-02 11:19 UTC, merged